### ISSUE TITLE
网站每个工具库的卡片在悬停时鼠标仍然是箭头， 而不是可点击的手型

### ISSUE THREAD

**Issue by gongwlin** [docschina/docschina-issue-discussions-open#1]
例如第一个前端框架模块的react库，  悬停时鼠标仍然是箭头， 而不是可点击的手型， 可添加如下css代码
```css
.dc-card-item-bg:hover {
    cursor: pointer;
}
```
